### ISSUE TITLE
Love the project , i have a suggestion

### ISSUE THREAD

**Issue by SamuelLachance** [andrewderango/IceAnalytics#79]
would be very nice if we could see prediction by date , like past date and future dates . Ty

**Comment by andrewderango** [comment]
Hi Samuel, thanks for your interest and suggestion. I do have a feature planned so that users can see game probabilities from different dates by toggling dates. I'll let you know when this is released.

**Comment by andrewderango** [comment]
Implemented in [v1.1.0](https://github.com/andrewderango/IceAnalytics/releases/tag/v1.1.0).
